---
title: "p8105_hw2_sw3737"
output: github_document
date: "2023-10-04"
---

```{r setup, message=FALSE}
library(tidyverse)
```

## Problem 1

```{r import}
pols_data <- read.csv("data_files_hw2/pols-month.csv")
snp_data <- read.csv("data_files_hw2/snp.csv")
unemployment_data <- read.csv("data_files_hw2/unemployment.csv")
```

```{r pols cleaning}
cleaned_pols <- pols_data %>%
  separate(mon, into = c("year", "month", "day"), sep = "-") %>%
  mutate(year = as.integer(year),
         month = month.abb[as.integer(month)],
         president = ifelse(prez_dem == 1, "dem", "gop")) %>%
  select(-day, -prez_dem, -prez_gop)
```

```{r snp cleaning}
cleaned_snp <- snp_data %>%
  separate(date, into = c("year", "month", "day"), sep = "-") %>%
  mutate(year = as.integer(year),
         month = month.abb[as.integer(month)]) %>%
  select(year, month, everything()) %>%
  arrange(year, month)
```

```{r unemployment cleaning}
tidied_unemployment <- unemployment_data %>%
  rename(year = Year) %>%
  gather(key = "month", value = "unemployment_rate", -year) %>%
  mutate(month = match(month, month.abb))
```

```{r merging}
merged_data <- cleaned_pols %>%
  left_join(cleaned_snp, by = c("year", "month")) %>%
  left_join(tidied_unemployment, by = c("year", "month"))
```